--- 
title: "Advanced Analysis" 
output: pdf_document 
geometry: "top=3.5cm, bottom=3cm" 
header-includes: 
- \usepackage{booktabs} 
- \usepackage{sectsty} 
- \usepackage{titlesec} 
- \titleformat*{\section}{\raggedleft\Large\bfseries} 
- \newcommand{\sectionbreak}{\clearpage\vspace*{.35\textheight}} 
--- 

# For PP: 

\newpage 
## Linear Modelling 

----- 

Our Linear Model: 
$$ 
 \Delta ln(\bar{PP}) = 1 + Group + Activity + 1|Subject 
$$ 

----- 

```{r echo = FALSE, warning = FALSE, message = FALSE} 

library(tidyverse) 
library(knitr) 
library(grid) 
library(gridExtra) 
library(kableExtra) 
library(nlme) 
library(wesanderson) 

# READING IN CSV FILES 
testing_df <- read_csv("~/Desktop/testing_df.csv", col_types = cols()) 
testing_df <- testing_df %>% 
  mutate(Condition = factor(Condition, levels = c("BL", "IL", "BH", "IH"))) 
colnames(testing_df)[which(names(testing_df) == "Condition")] <- "Group" 

age_df <- read_csv("~/Desktop/Stress_Project/Pre-SurveyExport.csv", col_types = cols()) 
age_df <- age_df[, c(22, 23, 24, 25, 27, 29, 30, 19)] 
names(age_df) <- c("Subject", "Age", "Gender", "Nationality", "NativeLanguage", "EducationLevel", "Occupation", "City") 

# MERGING CSV FILES 
diff_df <- testing_df[ , c(1:3, 9:18)] 
names <- names(diff_df)[!(names(diff_df) %in% c("WB.RB", "SC.RB", "SC.WB", "DT.RB", "DT.WB", "DT.SC", "P.RB", "P.WB", "P.SC", "P.DT"))] 
diff_df <- diff_df %>% 
  gather(Session, PP, -names) %>% 
  mutate(Session = factor(Session, levels = c("WB.RB", "SC.RB", "SC.WB", "DT.RB", "DT.WB", "DT.SC", "P.RB", "P.WB", "P.SC", "P.DT"))) %>% 
  filter(Session %in% c("WB.RB", "SC.RB", "DT.RB", "P.RB")) %>% 
  filter(Measurement == "PP") %>% 
  mutate(PP = log(PP)) 
levels(diff_df$Session) <- c("WB", "SC", "SC.WB", "DT", "DT.WB", "DT.SC", "P", "P.WB", "P.SC", "P.DT") 
# diff_df <- merge(diff_df, age_df, by = "Subject") 

# CREATING LINEAR MODELS 
fit3_diff <- lme(PP ~ 1 + Group + Session, data = diff_df, random = ~1|Subject, na.action = na.omit) 

# SUMMARIZING LINEAR MODELS 
print(summary(fit3_diff)) 
``` 

\newpage 
## PP Measures for Emails vs Essay Writing 
```{r echo = FALSE, warning = FALSE, message = FALSE} 

give.n.half <- function(x) { 
  return(c(y=-Inf, vjust = -1, label=length(x) / 2)) 
} 

interpret_results <- function(p_value) { 
  if (p_value > 0.05) { 
    return(" ") 
  } else if (p_value <= 0.001) { 
    return("***") 
  } else if (p_value <= 0.01) { 
    return("**") 
  } else if (p_value <= 0.05) { 
    return("*") 
  } 
} 

interpret_results_after <- function(p_value, name, test = "Paired t-test") { 
  if (p_value > 0.05) { 
    result <- paste0(test, "\n", name, " p = ", round(p_value, 4), " > 0.05\n\n") 
  } else if (p_value <= 0.001) { 
    result <- paste0(test, "\n", name, " p = ", round(p_value, 4), " < 0.001  ***\n\n") 
  } else if (p_value <= 0.01) { 
    result <- paste0(test, "\n", name, " p = ", round(p_value, 4), " < 0.01  **\n\n") 
  } else if (p_value <= 0.05) { 
    result <- paste0(test, "\n", name, " p = ", round(p_value, 4), " < 0.05  *\n\n") 
  } 
  return(result) 
} 

# CHANGE THIS 
# The file path, that is. 
full_df <- read_csv("~/Desktop/full_df.csv", col_types = cols()) 

# Just taking some columns from the global tibble that we need and getting rid of the rest of them. 
result_df <- full_df[ , c("Subject", "Condition", "Session", "CovertedTime", "TimeElapsed", "PP", "Task")] 

result_df <- result_df %>% 
  mutate(PP = log(PP)) 

rb_mean_df <- result_df %>% 
  filter(Session == "RestingBaseline") %>% 
  group_by(Subject, Condition) %>% 
  summarize(meanRB = mean(PP, na.rm = TRUE)) 

essay_df <- result_df %>% 
  filter(Task == "Essay") %>% 
  group_by(Subject, Condition) %>% 
  summarize(Essay = mean(PP, na.rm = TRUE)) 

email_df <- result_df %>% 
  filter(Task == "Email") %>% 
  group_by(Subject, Condition) %>% 
  summarize(Email = mean(PP, na.rm = TRUE)) 

total_df <- merge(rb_mean_df, essay_df, by = c("Subject", "Condition")) 
total_df <- merge(total_df, email_df, by = c("Subject", "Condition")) 

total_df <- total_df %>% 
  na.omit() %>% 
  mutate(Essay = Essay - meanRB) %>% 
  mutate(Email = Email - meanRB) 

result_sig <- interpret_results(t.test(total_df$Essay, total_df$Email, data = total_df, paired = TRUE)$p.value) 
result <- interpret_results_after(t.test(total_df$Essay, total_df$Email, data = total_df, paired = TRUE)$p.value, "For all groups,") 

grouped_sign_vec <- NULL 
result_grouped_vec <- NULL 
cond_df <- total_df %>% 
  filter(Condition %in% c("IH", "IL")) 
grouped_sign_vec[1] <- interpret_results(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value) 
result_grouped_vec[1] <- interpret_results_after(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value, "For Intermittent,") 

cond_df <- total_df %>% 
  filter(Condition %in% c("BH", "BL")) 
grouped_sign_vec[2] <- interpret_results(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value) 
result_grouped_vec[2] <- interpret_results_after(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value, "For Batch,") 

condition_levels <- c("IH", "IL", "BH", "BL") 
sign_vec <- NULL 
result_vec <- NULL 
i <- 1 
for (cond in condition_levels) { 
  cond_df <- total_df %>% 
    filter(Condition == cond) 
  
  sign_vec[i] <- interpret_results(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value) 
  result_vec[i] <- interpret_results_after(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value, paste0("For ", cond, ",")) 
  i <- i + 1 
} 

whole_df <- total_df %>% 
  gather(Task, Value, -Subject, -Condition, -meanRB) 

total_grouped_df <- total_df %>% 
  gather(Task, Value, -Subject, -Condition, -meanRB) 

total_df <- total_df %>% 
  gather(Task, Value, -Subject, -Condition, -meanRB) 

whole_df[ , "Condition"] <- "All" 
print( 
  whole_df %>% 
    ggplot(aes(x = Condition, y = Value, color = Task)) + 
      geom_boxplot() + 
      geom_hline(yintercept=0, linetype="dashed", color = "red", alpha = 0.6, size = 1) + 
      theme_bw() + 
      ggtitle(" ") + 
      ylab(bquote(paste('Normalized Perinasal Perspiration [',''^'o','C',''^2,']'))) + 
      theme(axis.title.x=element_blank(), axis.text.x = element_text(size = 10), 
            legend.position="bottom") + 
      stat_summary(fun.data = give.n.half, geom = "text", color = "black") + 
      scale_y_continuous(expand = c(0.15, 0, 0.3, 0)) + 
      annotate("text", x=1, y=Inf, label= result_sig, vjust = 1.2, size = 8) 
) 

cat(result) 

total_grouped_df[total_grouped_df$Condition == "IH", "Condition"] <- "Intermittent" 
total_grouped_df[total_grouped_df$Condition == "IL", "Condition"] <- "Intermittent" 
total_grouped_df[total_grouped_df$Condition == "BH", "Condition"] <- "Batch" 
total_grouped_df[total_grouped_df$Condition == "BL", "Condition"] <- "Batch" 

total_grouped_df <- total_grouped_df %>% 
    mutate(Condition = factor(Condition)) 

print( 
  total_grouped_df %>% 
    mutate(Condition = factor(Condition, levels = c("Intermittent", "Batch"))) %>% 
    group_by(Condition) %>% 
    ggplot(aes(x = Condition, y = Value, color = Task)) + 
      geom_boxplot() + 
      geom_hline(yintercept=0, linetype="dashed", color = "red", alpha = 0.6, size = 1) + 
      theme_bw() + 
      ggtitle(" ") + 
      ylab(bquote(paste('Normalized Perinasal Perspiration [',''^'o','C',''^2,']'))) + 
      theme(axis.title.x=element_blank(), axis.text.x = element_text(size = 10), 
            legend.position="bottom") + 
      stat_summary(fun.data = give.n.half, geom = "text", color = "black") + 
      scale_y_continuous(expand = c(0.15, 0, 0.3, 0)) + 
      annotate("text", x=1, y=Inf, label= grouped_sign_vec[1], vjust = 1.2, size = 8) + 
      annotate("text", x=2, y=Inf, label= grouped_sign_vec[2], vjust = 1.2, size = 8) 
) 

cat(result_grouped_vec[1]) 
cat(result_grouped_vec[2]) 

print( 
  total_df %>% 
    mutate(Condition = factor(Condition, levels = condition_levels)) %>% 
    group_by(Condition) %>% 
    ggplot(aes(x = Condition, y = Value, fill = Task)) + 
      geom_boxplot() + 
      geom_hline(yintercept=0, linetype="dashed", color = "red", alpha = 0.6, size = 1) + 
      theme_bw() + 
      ggtitle(" ") + 
      ylab(expression(Delta~paste('ln(PP) [',''^'o','C',''^2,']'))) + 
      theme(axis.title.x=element_blank(), 
            legend.position="bottom", 
            axis.text = element_text(size=14), 
            axis.title = element_text(size=16, face="bold")) + 
      #stat_summary(fun.data = give.n, geom = "text", color = "black") + 
      scale_y_continuous(expand = c(0.05, 0, 0.15, 0)) + 
      annotate("text", x=1, y=Inf, label= sign_vec[1], vjust = 1.2, size = 8) + 
      annotate("text", x=2, y=Inf, label= sign_vec[2], vjust = 1.2, size = 8) + 
      annotate("text", x=3, y=Inf, label= sign_vec[3], vjust = 1.2, size = 8) + 
      annotate("text", x=4, y=Inf, label= sign_vec[4], vjust = 1.2, size = 8) + 
      scale_fill_manual(labels = c("Emails", "Report"), values = c("#E2D200", "#DD8D28")) + 
      scale_x_discrete(labels = c("IF", "IR", "BF", "BR")) 
) 

cat(result_vec[1]) 
cat(result_vec[2]) 
cat(result_vec[3]) 
cat(result_vec[4]) 

``` 

\newpage 
## More Linear Modelling 

----- 

Our Linear Model: 
$$ 
 \Delta ln(\bar{PP}) = 1 + Group + Dual Task + 1|Subject 
$$ 

----- 



```{r echo = FALSE, warning = FALSE, message = FALSE} 

colnames(total_df)[which(names(total_df) == "Value")] <- "PP" 
colnames(total_df)[which(names(total_df) == "Condition")] <- "Group" 
colnames(total_df)[which(names(total_df) == "Task")] <- "DualTask" 

total_df <- total_df %>% 
  mutate(Group = factor(Group)) %>% 
  mutate(Group = factor(Group, levels = c("BL", "IL", "BH", "IH"))) %>% 
  mutate(DualTask = factor(DualTask)) %>% 
  mutate(DualTask = factor(DualTask, levels = c("Email", "Essay"))) 

# CREATING LINEAR MODELS 
fit_dt <- lme(PP ~ 1 + Group + DualTask, data = total_df, random = ~1|Subject, na.action = na.omit) 

# SUMMARIZING LINEAR MODELS 
print(summary(fit_dt)) 
``` 

# For HR: 

\newpage 
## Linear Modelling 

----- 

Our Linear Model: 
$$ 
 \Delta HR = 1 + Group + Session + 1|Subject 
$$ 

----- 

```{r echo = FALSE, warning = FALSE, message = FALSE} 

# MERGING CSV FILES 
diff_df <- testing_df[ , c(1:3, 9:18)] 
names <- names(diff_df)[!(names(diff_df) %in% c("WB.RB", "SC.RB", "SC.WB", "DT.RB", "DT.WB", "DT.SC", "P.RB", "P.WB", "P.SC", "P.DT"))] 
diff_df <- diff_df %>% 
  gather(Session, HR, -names) %>% 
  mutate(Session = factor(Session, levels = c("WB.RB", "SC.RB", "SC.WB", "DT.RB", "DT.WB", "DT.SC", "P.RB", "P.WB", "P.SC", "P.DT"))) %>% 
  filter(Session %in% c("WB.RB", "SC.RB", "DT.RB", "P.RB")) %>% 
  filter(Measurement == "HR") 
levels(diff_df$Session) <- c("WB", "SC", "SC.WB", "DT", "DT.WB", "DT.SC", "P", "P.WB", "P.SC", "P.DT") 
diff_df <- merge(diff_df, age_df, by = "Subject") 

# CREATING LINEAR MODELS 
fit3_diff <- lme(HR ~ 1 + Group + Session, data = diff_df, random = ~1|Subject, na.action = na.omit) 

# SUMMARIZING LINEAR MODELS 
print(summary(fit3_diff)) 
``` 

\newpage 
## HR Measures for Emails vs Essay Writing 
```{r echo = FALSE, warning = FALSE, message = FALSE} 

# CHANGE THIS 
# The file path, that is. 
full_df <- read_csv("~/Desktop/full_df.csv", col_types = cols()) 

# Just taking some columns from the global tibble that we need and getting rid of the rest of them. 
result_df <- full_df[ , c("Subject", "Condition", "Session", "CovertedTime", "TimeElapsed", "HR", "Task")] 

rb_mean_df <- result_df %>% 
  filter(Session == "RestingBaseline") %>% 
  group_by(Subject, Condition) %>% 
  summarize(meanRB = mean(HR, na.rm = TRUE)) 

essay_df <- result_df %>% 
  filter(Task == "Essay") %>% 
  group_by(Subject, Condition) %>% 
  summarize(Essay = mean(HR, na.rm = TRUE)) 

email_df <- result_df %>% 
  filter(Task == "Email") %>% 
  group_by(Subject, Condition) %>% 
  summarize(Email = mean(HR, na.rm = TRUE)) 

total_df <- merge(rb_mean_df, essay_df, by = c("Subject", "Condition")) 
total_df <- merge(total_df, email_df, by = c("Subject", "Condition")) 

total_df <- total_df %>% 
  na.omit() %>% 
  mutate(Essay = Essay - meanRB) %>% 
  mutate(Email = Email - meanRB) 

result_sig <- interpret_results(t.test(total_df$Essay, total_df$Email, data = total_df, paired = TRUE)$p.value) 
result <- interpret_results_after(t.test(total_df$Essay, total_df$Email, data = total_df, paired = TRUE)$p.value, "For all groups,") 

grouped_sign_vec <- NULL 
result_grouped_vec <- NULL 
cond_df <- total_df %>% 
  filter(Condition %in% c("IH", "IL")) 
grouped_sign_vec[1] <- interpret_results(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value) 
result_grouped_vec[1] <- interpret_results_after(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value, "For Intermittent,") 

cond_df <- total_df %>% 
  filter(Condition %in% c("BH", "BL")) 
grouped_sign_vec[2] <- interpret_results(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value) 
result_grouped_vec[2] <- interpret_results_after(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value, "For Batch,") 

condition_levels <- c("IH", "BH", "IL", "BL") 
sign_vec <- NULL 
result_vec <- NULL 
i <- 1 
for (cond in condition_levels) { 
  cond_df <- total_df %>% 
    filter(Condition == cond) 
  
  sign_vec[i] <- interpret_results(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value) 
  result_vec[i] <- interpret_results_after(t.test(cond_df$Essay, cond_df$Email, data = cond_df, paired = TRUE)$p.value, paste0("For ", cond, ",")) 
  i <- i + 1 
} 

whole_df <- total_df %>% 
  gather(Task, Value, -Subject, -Condition, -meanRB) 

total_grouped_df <- total_df %>% 
  gather(Task, Value, -Subject, -Condition, -meanRB) 

total_df <- total_df %>% 
  gather(Task, Value, -Subject, -Condition, -meanRB) 

whole_df[ , "Condition"] <- "All" 
print( 
  whole_df %>% 
    ggplot(aes(x = Condition, y = Value, color = Task)) + 
      geom_boxplot() + 
      geom_hline(yintercept=0, linetype="dashed", color = "red", alpha = 0.6, size = 1) + 
      theme_bw() + 
      ggtitle(" ") + 
      ylab(bquote(paste('Normalized Perinasal Perspiration [',''^'o','C',''^2,']'))) + 
      theme(axis.title.x=element_blank(), axis.text.x = element_text(size = 10), 
            legend.position="bottom") + 
      stat_summary(fun.data = give.n.half, geom = "text", color = "black") + 
      scale_y_continuous(expand = c(0.15, 0, 0.3, 0)) + 
      annotate("text", x=1, y=Inf, label= result_sig, vjust = 1.2, size = 8) 
) 

cat(result) 

total_grouped_df[total_grouped_df$Condition == "IH", "Condition"] <- "Intermittent" 
total_grouped_df[total_grouped_df$Condition == "IL", "Condition"] <- "Intermittent" 
total_grouped_df[total_grouped_df$Condition == "BH", "Condition"] <- "Batch" 
total_grouped_df[total_grouped_df$Condition == "BL", "Condition"] <- "Batch" 

total_grouped_df <- total_grouped_df %>% 
    mutate(Condition = factor(Condition)) 

print( 
  total_grouped_df %>% 
    mutate(Condition = factor(Condition, levels = c("Intermittent", "Batch"))) %>% 
    group_by(Condition) %>% 
    ggplot(aes(x = Condition, y = Value, color = Task)) + 
      geom_boxplot() + 
      geom_hline(yintercept=0, linetype="dashed", color = "red", alpha = 0.6, size = 1) + 
      theme_bw() + 
      ggtitle(" ") + 
      ylab(bquote(paste('Normalized Perinasal Perspiration [',''^'o','C',''^2,']'))) + 
      theme(axis.title.x=element_blank(), axis.text.x = element_text(size = 10), 
            legend.position="bottom") + 
      stat_summary(fun.data = give.n.half, geom = "text", color = "black") + 
      scale_y_continuous(expand = c(0.15, 0, 0.3, 0)) + 
      annotate("text", x=1, y=Inf, label= grouped_sign_vec[1], vjust = 1.2, size = 8) + 
      annotate("text", x=2, y=Inf, label= grouped_sign_vec[2], vjust = 1.2, size = 8) 
) 

cat(result_grouped_vec[1]) 
cat(result_grouped_vec[2]) 

print( 
  total_df %>% 
    mutate(Condition = factor(Condition, levels = condition_levels)) %>% 
    group_by(Condition) %>% 
    ggplot(aes(x = Condition, y = Value, fill = Task)) + 
      geom_boxplot() + 
      geom_hline(yintercept=0, linetype="dashed", color = "red", alpha = 0.6, size = 1) + 
      theme_bw() + 
      ggtitle(" ") + 
      ylab(expression(Delta~"ln(HR)")) + 
      theme(axis.title.x=element_blank(), 
            legend.position="bottom", 
            axis.text = element_text(size=14), 
            axis.title = element_text(size=16, face="bold")) + 
      stat_summary(fun.data = give.n.half, geom = "text", color = "black") + 
      scale_y_continuous(expand = c(0.15, 0, 0.3, 0)) + 
      annotate("text", x=1, y=Inf, label= sign_vec[1], vjust = 1.2, size = 8) + 
      annotate("text", x=2, y=Inf, label= sign_vec[2], vjust = 1.2, size = 8) + 
      annotate("text", x=3, y=Inf, label= sign_vec[3], vjust = 1.2, size = 8) + 
      annotate("text", x=4, y=Inf, label= sign_vec[4], vjust = 1.2, size = 8) + 
      scale_fill_manual(values = c("#E2D200", "#DD8D28")) 
) 

cat(result_vec[1]) 
cat(result_vec[2]) 
cat(result_vec[3]) 
cat(result_vec[4]) 

``` 

\newpage 
## More Linear Modelling 

----- 

Our Linear Model: 
$$ 
 \Delta HR = 1 + Group + Dual Task + 1|Subject 
$$ 

----- 



```{r echo = FALSE, warning = FALSE, message = FALSE} 

colnames(total_df)[which(names(total_df) == "Value")] <- "HR" 
colnames(total_df)[which(names(total_df) == "Condition")] <- "Group" 
colnames(total_df)[which(names(total_df) == "Task")] <- "DualTask" 

total_df <- total_df %>% 
  mutate(Group = factor(Group)) %>% 
  mutate(Group = factor(Group, levels = c("BL", "IL", "BH", "IH"))) %>% 
  mutate(DualTask = factor(DualTask)) %>% 
  mutate(DualTask = factor(DualTask, levels = c("Email", "Essay"))) 

# CREATING LINEAR MODELS 
fit_dt <- lme(HR ~ 1 + Group + DualTask, data = total_df, random = ~1|Subject, na.action = na.omit) 

# SUMMARIZING LINEAR MODELS 
print(summary(fit_dt)) 
```  
